name: 'Review Commit Action'
description: 'Wait for approval from a repository collaborator via reaction on a commit comment'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: false
    default: ${{ github.token }}
  check-interval:
    description: 'Interval in seconds between checks for reactions'
    required: false
    default: '10'

outputs:
  comment-id:
    description: 'ID of the commit comment'
  approved-by:
    description: 'Login of the user who approved the commit'
  rejected-by:
    description: 'Login of the user who rejected the commit'

runs:
  using: 'node20'
  main: 'index.js'
